<a href="https://colab.research.google.com/github/wilwil186/MAConPython/blob/main/T2metodos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Wilson Eduardo Jerez Hernández
## 20181167034

1. Construya un código lo más sencillo posible para hacer sustitución hacia atrás de una matriz triangular superior.


In [34]:
import numpy as np #importamos numpara para usar la función array 
#creamos una función que resiva como aprametros dos matrices
def CMTSuperior(A,B):
  for i in range(len(B)-1):
    B[i]=B[i]/A[i][i]
    A[i]=A[i]/A[i][i]
    for k in range(i+1,N):
      B[k]=B[k]-A[k][i]*B[i]
      A[k]=A[k]-A[k][i]*A[i]
  print('matriz de incognitas')
  print(A)
  print('matriz de coeficientes')
  print(B)
  
  return (A,B)

Posteriormente, contruya el código sencillo del método de gauus haciendo primero reducción a matriz triangular usando **pivoteo parcial** y luego usando la función de sustitución hacia atrás construida en el primer punto. 

In [31]:
def SA(A,B): # la matriz A debe pasar primero por la función anterior
  for i in reversed(range(N)): #ciclo en reversa
    suma=np.sum(A[i][i+1:]*x[i+1:])
    x[i]=B[i]-suma

  print("solución")
  print(x)

2. Resuelva el siguiente sistema de ecuaciones de manera manual usando pivoteo parcial y luego verifique su respuesta con el programa realizado en primer punto y agregue la salida del programa. 

In [35]:


A = np.array([[80,-50,-30,0],
              [-50,100,-10,-15],
              [-30,-10,65,-20],
              [0,-25,-20,100]])
B = np.array([
    [120],
    [0],
    [0],
    [0]
])
CMTSuperior(A,B)

matriz de incognitas
[[  1   0   0   0]
 [  0   1   0   0]
 [  0   0   1   0]
 [  0   0   0 100]]
matriz de coeficientes
[[1]
 [0]
 [0]
 [0]]


(array([[  1,   0,   0,   0],
        [  0,   1,   0,   0],
        [  0,   0,   1,   0],
        [  0,   0,   0, 100]]), array([[1],
        [0],
        [0],
        [0]]))

In [37]:
SA(A,B)

solución
[1. 0. 0. 0.]


3. Use el programa de Muller para hallar una raiz del polinomio $x^{3}-13x-12$ partiendo de los puntos semilla $x_{0}=4.5,x_{1}=5.5,x_{2}=5$ tenga en cuenta que el error relativo sea menor o igual a $0.03\%$. ¿Cuántas iteraciones realizó para alcanzar la aproximación?

In [38]:
from numpy import sign
from numpy.lib.scimath import sqrt


def muller(f, x0, x1, x2, tol):
    error = 1e3
    x3 = 0
    while error > tol:
        c = f(x2)
        b = ((x0 - x2)**2 * (f(x1) - f(x2)) - (x1 - x2)**2 *
             (f(x0) - f(x2))) / ((x0 - x2) * (x1 - x2) * (x0 - x1))
        a = ((x1 - x2) * (f(x0) - f(x2)) - (x0 - x2) *
             (f(x1) - f(x2))) / ((x0 - x2) * (x1 - x2) * (x0 - x1))
        x3 = x2 - (2 * c) / (b + sign(b) * sqrt(b**2 - 4 * a * c))
        error = abs(x3 - x2)
        x0 = x1
        x1 = x2
        x2 = x3
    return x3

In [41]:
f = lambda x: x**3-13*x-12
x0 = 4.5
x1 = 5.5 
x2 = 5
tol = 0.03/100
muller(f,x0,x1,x2,tol)

4.000000000000497